# .. name is how you install it with composer | composer req tutorial/site-agency
name: 'neon/tx-team'
label: 'Team Member'
# ... define your dependencies
dependencies:
  - typo3/fluid-styled-content
  - typo3/fluid-styled-content-css

settings:
  # ... rest of your settings